name: CI

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "./static/**"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "./static/**"
  pull_request_review:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      
      # go
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.16'
      
      - name: make lmp
        run: |
          go build -o lmp main.go

